name: Auto Merge My Bash PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  validate-and-merge:
    if: >
      github.event.pull_request.user.login == 'maglovskiNenad' &&
      github.event.pull_request.base.ref == 'main' &&
      github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Bash syntax
        run: |
          find . -type f -name "*.sh" -print0 |
          xargs -0 -r -n1 bash -n

      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        run: |
          find . -type f -name "*.sh" -print0 |
          xargs -0 -r shellcheck

      - name: Auto merge pull request
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
